// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: claim.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Claim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClaimId       int64                  `protobuf:"varint,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"` // field numbers are forever
	ClaimType     string                 `protobuf:"bytes,2,opt,name=claim_type,json=claimType,proto3" json:"claim_type,omitempty"`
	ClaimAmount   int64                  `protobuf:"varint,3,opt,name=claim_amount,json=claimAmount,proto3" json:"claim_amount,omitempty"` // optional presence: see below
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Claim) Reset() {
	*x = Claim{}
	mi := &file_claim_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Claim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claim) ProtoMessage() {}

func (x *Claim) ProtoReflect() protoreflect.Message {
	mi := &file_claim_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claim.ProtoReflect.Descriptor instead.
func (*Claim) Descriptor() ([]byte, []int) {
	return file_claim_proto_rawDescGZIP(), []int{0}
}

func (x *Claim) GetClaimId() int64 {
	if x != nil {
		return x.ClaimId
	}
	return 0
}

func (x *Claim) GetClaimType() string {
	if x != nil {
		return x.ClaimType
	}
	return ""
}

func (x *Claim) GetClaimAmount() int64 {
	if x != nil {
		return x.ClaimAmount
	}
	return 0
}

func (x *Claim) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Claim) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Claim) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_claim_proto protoreflect.FileDescriptor

const file_claim_proto_rawDesc = "" +
	"\n" +
	"\vclaim.proto\x12\vprotobufsrc\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd9\x01\n" +
	"\x05Claim\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\x03R\aclaimId\x12\x1d\n" +
	"\n" +
	"claim_type\x18\x02 \x01(\tR\tclaimType\x12!\n" +
	"\fclaim_amount\x18\x03 \x01(\x03R\vclaimAmount\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescriptionB?Z=policymanagement/dataserialization/protobufsrc/gen/demo/v1;v1b\x06proto3"

var (
	file_claim_proto_rawDescOnce sync.Once
	file_claim_proto_rawDescData []byte
)

func file_claim_proto_rawDescGZIP() []byte {
	file_claim_proto_rawDescOnce.Do(func() {
		file_claim_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_claim_proto_rawDesc), len(file_claim_proto_rawDesc)))
	})
	return file_claim_proto_rawDescData
}

var file_claim_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_claim_proto_goTypes = []any{
	(*Claim)(nil),                 // 0: protobufsrc.Claim
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_claim_proto_depIdxs = []int32{
	1, // 0: protobufsrc.Claim.created_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_claim_proto_init() }
func file_claim_proto_init() {
	if File_claim_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_claim_proto_rawDesc), len(file_claim_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_claim_proto_goTypes,
		DependencyIndexes: file_claim_proto_depIdxs,
		MessageInfos:      file_claim_proto_msgTypes,
	}.Build()
	File_claim_proto = out.File
	file_claim_proto_goTypes = nil
	file_claim_proto_depIdxs = nil
}
